hasItems = [
    { name: 'たけのこランプ', count: 2 },
    { name: 'ガーデンベンチ', count: 1 },
    { name: 'つみきテーブル', count: 1 },
    { name: 'たけのステッキ', count: 1 },
    { name: 'まるたのスツール', count: 1 },
    { name: 'かめ', count: 1 },
    { name: 'スワッグ', count: 1 },
    { name: 'チューリップのビックリばこ', count: 1 },
    { name: 'いぬごや', count: 1 },
    { name: 'ジャングルのかべがみ', count: 2 },
    { name: 'きんのアロワナ', count: 1 },
    { name: 'マネーなゆか', count: 2 },
    { name: 'こしみの', count: 1 },
    { name: 'パンジーのテーブル', count: 1 },
    { name: 'みの', count: 1 },
    { name: 'ひくいにわいし', count: 1 },
    { name: 'かせきのドアプレート', count: 1 },
    { name: 'パンジーのかんむり・パープル', count: 1 },
    { name: 'ケトルベル', count: 1 },
    { name: 'おうごんのしょくだい', count: 1 },
    { name: 'もくせいのほんだな', count: 1 },
  ]